#!/bin/sh

# base off this https://github.com/acrogenesis/macchanger but in bash bc
help="usage: macchanger [options] [device]\n"
help+=" \n"
help+="options:\n"
help+="-m, --mac MAC             Set the MAC address,    macchanger -m XX:XX:XX:XX:XX:XX en0\n"
help+="-r, --random              Set random MAC address, macchanger -r en0\n"
help+="-s, --show                Show the MAC address,   macchanger -s en0"

if (($# > 0)); then
    case "$1" in
        -m|--mac)
            if (($# > 2)); then
                DEVICE=$2
                NEWMAC=$3
            else
                echo "macchanger: no device or mac address specified"
            fi
            ;;
        -r|--random)
            if (($# > 1)); then
                DEVICE=$2
                if hash openssl 2>/dev/null; then
                    NEWMAC="$(openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//')"
                else
                    NEWMAC="$(printf '%02X:%02X:%02X:%02X:%02X:%02X\n' \
                        $((RANDOM%256)) $((RANDOM%256)) \
                        $((RANDOM%256)) $((RANDOM%256)) \
                        $((RANDOM%256)) $((RANDOM%256)))"
                fi
            else
                echo "macchanger: no device specified"
            fi
            ;;
        -s|--show)
            if (($# > 1)); then
                ifconfig "$2" | grep --color=never ether | cut -c 8- | head -1
            else
                echo "macchanger: no device specified"
            fi
            ;;
        *)
            echo "$help"
            ;;
    esac
else
    echo "$help"
fi

if [ -n "$DEVICE" ] && [ -n "$NEWMAC" ]; then
    sudo ifconfig "$DEVICE" ether "$NEWMAC" && \
        echo "$DEVICE => $NEWMAC"
fi

