#!/bin/bash

help() {
    echo "usage: macchanger [options] [device]"
    echo " "
    echo "options:"
    echo "-m, --mac                 Set the MAC address,    macchanger -m en0 XX:XX:XX:XX:XX:XX"
    echo "-r, --random              Set random MAC address, macchanger -r en0"
    echo "-s, --show                Show the MAC address,   macchanger -s en0"
}

OS() {
    if [[ "$OSTYPE" == darwin* ]]; then
        echo 'OSX'
    elif [[ "$OSTYPE" == linux-gnu* ]]; then
        echo 'linux'
    else
        echo 'unknown'
    fi
}

MAC() {
    if [ "$(OS)" == "OSX" ]; then
        ifconfig "$1" | grep --color=never ether | cut -c 8-
    else
        ifconfig "$1" | grep --color=never HWaddr | rev | cut -c 3-19 | rev
    fi
}

generateMAC() {
    if hash openssl 2>/dev/null; then
        openssl rand -hex 6 | sed 's/\(..\)/\1:/g; s/.$//'
    else
        printf '%02X:%02X:%02X:%02X:%02X:%02X\n' \
            $((RANDOM%256)) $((RANDOM%256)) \
            $((RANDOM%256)) $((RANDOM%256)) \
            $((RANDOM%256)) $((RANDOM%256))
    fi
}

changeMAC() {
    DEVICE=$1
    NEWMAC=$2
    sudo ifconfig "$DEVICE" ether "$NEWMAC" && \
        echo "$DEVICE => $(MAC "$DEVICE")"
}

# $2 = device, $3 = MAC address
if (($# > 0)); then
    case "$1" in
        -m|--mac)
            if (($# > 2)); then
                changeMAC "$2" "$3"
            else
                echo "macchanger: no device or mac address specified"
                exit 1
            fi
            ;;
        -r|--random)
            if (($# > 1)); then
                changeMAC "$2" "$(generatedMAC)"
            else
                echo "macchanger: no device specified"
                exit 1
            fi
            ;;
        -s|--show)
            if (($# > 1)); then
                MAC "$2"
            else
                echo "macchanger: no device specified"
                exit 1
            fi
            ;;
        *)
            help
            ;;
    esac
else
    help
fi
